# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
relative_permalinks: true
#pretty
permalink:           /blog/:year/:month/:day/:title/
#categories:
#  projects:
#    permalink:           projects/:year/:month/:day/:title/
collections:
  projects:
    output: true


# Setup
title:               'The Blog of Yohannes'
tagline:             'Full-Stack Engineer'
description:         'A Technical blog about web development and few other things.'
url: 'http://yohanneshl.github.io'
baseurl:              '/'
paginate:            3
paginate_path: "blog/page:num/"
# About/contact
author:
  name:              Yohannes Libanos
  role:              '&middot Full-Stack Engineer'
  url:               https://twitter.com/mdo
  email:             4yohannes@gmail.com

github:              https://github.com/yohanneshl
linkedin:            https://www.linkedin.com/in/yohanneslibanos
# Custom vars
